package com.excelsies.hycolonies.logistics.model;

import java.util.UUID;

/**
 * Represents an instruction for a courier to transport items from source to destination.
 * Generated by the LogisticsSolver and executed by the CourierJobSystem.
 */
public record TransportInstruction(
    UUID instructionId,
    UUID courierId,
    WarehouseLocation source,
    WarehouseLocation destination,
    String itemId,
    int quantity,
    RequestPriority priority,
    long createdTime,
    UUID originalRequestId
) {
    /**
     * Creates a new transport instruction with auto-generated ID and timestamp.
     */
    public TransportInstruction(UUID courierId, WarehouseLocation source, WarehouseLocation destination,
                                 String itemId, int quantity, RequestPriority priority, UUID originalRequestId) {
        this(UUID.randomUUID(), courierId, source, destination, itemId, quantity,
             priority, System.currentTimeMillis(), originalRequestId);
    }

    /**
     * Returns true if this instruction involves the same item type as another.
     */
    public boolean sameItemAs(TransportInstruction other) {
        return itemId.equals(other.itemId);
    }

    /**
     * Returns the age of this instruction in milliseconds.
     */
    public long getAgeMs() {
        return System.currentTimeMillis() - createdTime;
    }

    /**
     * Returns true if this instruction is stale (older than threshold).
     */
    public boolean isStale(long maxAgeMs) {
        return getAgeMs() > maxAgeMs;
    }
}
